### ISSUE TITLE
Difference between Camera Matrix and Projection matrix for monocular camera calibration.

### ISSUE THREAD

**Issue by SubMishMar** [ros-perception/image_pipeline#499]
Below is the result I get with monocular camera calibration using the ros-camera calibrator. 

```
image_width: 800
image_height: 592
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [628.029818, 0.000000, 423.338953, 0.000000, 627.527774, 293.058025, 0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.084311, 0.019134, -0.000522, 0.002223, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000]
projection_matrix:
  rows: 3
  cols: 4
  data: [606.702637, 0.000000, 426.773232, 0.000000, 0.000000, 615.751648, 292.713433, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]
```

Since it is a monocular camera with no ROI as the full image, I was expecting the projection matrix to be same as the camera matrix (as explained here: https://docs.ros.org/melodic/api/sensor_msgs/html/msg/CameraInfo.html) but it is not so. Can anyone explain me why? I am not sure what I am missing here.
