### ISSUE TITLE
Issue rectifying 16bit mono images

### ISSUE THREAD

**Issue by LucidOne** [ros-perception/image_pipeline#55]
```
OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.widt
h <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in
 Mat, file /tmp/buildd/ros-hydro-opencv2-2.4.6-3precise-20140130-1852/modules/co
re/src/matrix.cpp, line 323
terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/buildd/ros-hydro-opencv2-2.4.6-3precise-20140130-1852/modules/co
re/src/matrix.cpp:323: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi
.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.row
s in function Mat
```

Launch File

```
  <group ns="/camera">
    <node pkg="nodelet" type="nodelet" name="rectify_mono"
      args="standalone image_proc/rectify" output="screen">
      <remap from="image_mono" to="image_raw" />
    </node>
  </group>
```

Here is the camera info
Image was decimated on-board the camera.

```
header: 
  seq: 9904
  stamp: 
    secs: 1392345058
    nsecs: 255573802
  frame_id: camera
height: 728
width: 968
distortion_model: plumb_bob
D: [-21.48163, 2154.22524, 0.24333000000000002, -0.24100000000000002, 0.0]
K: [6830.9773, 0.0, 437.66934, 0.0, 39782.98468, 304.66521, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [6439.25391, 0.0, 412.88838, 0.0, 0.0, 42096.67578, 324.95043, 0.0, 0.0, 0.0,
 1.0, 0.0]
binning_x: 2
binning_y: 2
roi: 
  x_offset: 0
  y_offset: 0
  height: 1456
  width: 1936
  do_rectify: True

---
```

Image header
rostopic echo --noarr /camera/image_raw

```
header: 
  seq: 9930
  stamp: 
    secs: 1392345061
    nsecs: 859107259
  frame_id: camera
height: 728
width: 968
encoding: mono16
is_bigendian: 0
step: 1936

---
```
