### ISSUE TITLE
point_cloud_xyzrgb_node errors:  RGB image has unsupported encoding [bgra8]

### ISSUE THREAD

**Issue by Alessio-Parmeggiani** [ros-perception/image_pipeline#964]
Hi, I got an error while running pointcloudXYZRGB node, it says the following error and it does not produce any pointcloud:
`[ERROR] [point_cloud_xyzrgb_node]: RGB image has unsupported encoding [bgra8]`

But looking in the code it seems that bgra8 is a supported format: [code](https://github.com/ros-perception/image_pipeline/blob/bae2fb952629d559b915c998e124f0b7643efc19/depth_image_proc/src/point_cloud_xyzrgb.cpp#L270)

The image is indeed of type bgra8, the following is one message from the camera:
```
header:
  stamp:
    sec: 1711115480
    nanosec: 428550000
  frame_id: zedxm_left_camera_optical_frame
height: 600
width: 960
encoding: bgra8
is_bigendian: 0
step: 3840
data: '<sequence type: uint8, length: 2304000>'
```

How can I solve this problem?
